import { build } from 'esbuild';
await build({
  entryPoints: ['src/main.ts'], bundle: true, external: ['obsidian'],
  format: 'cjs', target: 'es2020', platform: 'browser', outfile: 'main.js',
  banner: { js: '/* File Shortcuts — generated by npm run build. Source: src/main.ts */' },
});
