/* File Shortcuts — generated by npm run build. Source: src/main.ts */
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FileShortcutsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/dialogs.ts
var import_obsidian = require("obsidian");

// src/shortcut.ts
var EXTENSION = "obslink";
var VIEW_TYPE = "file-shortcut";
function validateTarget(path) {
  if (typeof path !== "string" || !path || path.startsWith("/") || /[\\\x00-\x1f:]/.test(path)) {
    throw new Error("The shortcut must point to a file inside this vault.");
  }
  if (path.split("/").some((part) => !part || part === "." || part === "..")) {
    throw new Error("The shortcut contains an invalid vault path.");
  }
  return path;
}
function parseShortcut(content) {
  let value;
  try {
    value = JSON.parse(content);
  } catch {
    throw new Error("This shortcut is not valid JSON. Choose a target file to repair it.");
  }
  if (!value || typeof value !== "object" || !("version" in value) || value.version !== 1 || !("target" in value)) {
    throw new Error("This file is not a supported version 1 shortcut.");
  }
  return { version: 1, target: validateTarget(value.target) };
}
function serializeShortcut(target) {
  return JSON.stringify({ version: 1, target: validateTarget(target) }, null, 2) + "\n";
}
function shortcutName(input) {
  const name = input.trim().replace(/\.obslink$/i, "").trim();
  if (!name || /[<>:"/\\|?*\x00-\x1f]/.test(name) || /[. ]$/.test(name) || name.startsWith(".")) {
    throw new Error("Enter a filename without slashes or special characters.");
  }
  if (/^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i.test(name)) {
    throw new Error("This filename is reserved on Windows. Please choose another name.");
  }
  if (name.length > 180) throw new Error("Please use a shorter shortcut name (180 characters or less).");
  return `${name}.${EXTENSION}`;
}
function movedTarget(target, oldPath, newPath, folder) {
  if (target === oldPath) return newPath;
  if (folder && target.startsWith(`${oldPath}/`)) return newPath + target.slice(oldPath.length);
  return target;
}
async function resolveShortcut(file, vault) {
  const visited = /* @__PURE__ */ new Set();
  let current = file;
  while (current.extension.toLowerCase() === EXTENSION) {
    if (visited.has(current.path)) throw new Error("These shortcuts form a loop. Choose a different target file.");
    if (visited.size >= 32) throw new Error("This shortcut chain is too long. Point it directly to the original file.");
    visited.add(current.path);
    const { target } = parseShortcut(await vault.read(current));
    const next = vault.getFile(target);
    if (!next) throw new Error(`Target file not found: ${target}`);
    current = next;
  }
  return current;
}

// src/dialogs.ts
var FilePicker = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, choose) {
    super(app);
    this.choose = choose;
    this.setPlaceholder("Choose the file to open");
  }
  getItems() {
    return this.app.vault.getFiles();
  }
  getItemText(file) {
    return file.path;
  }
  onChooseItem(file) {
    this.choose(file);
  }
};
var FolderPicker = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, choose) {
    super(app);
    this.choose = choose;
    this.setPlaceholder("Choose a folder for the shortcut");
  }
  getItems() {
    const root = this.app.vault.getRoot();
    const folders = this.app.vault.getAllLoadedFiles().filter((file) => file instanceof import_obsidian.TFolder && file !== root).sort((a, b) => a.path.localeCompare(b.path));
    return [root, ...folders];
  }
  getItemText(folder) {
    return folder.isRoot() ? "/ (vault root)" : folder.path;
  }
  onChooseItem(folder) {
    this.choose(folder);
  }
};
var CreateShortcutModal = class extends import_obsidian.Modal {
  constructor(app, target, folder, create) {
    super(app);
    this.target = target;
    this.folder = folder;
    this.create = create;
    this.busy = false;
    this.name = target.basename;
  }
  onOpen() {
    this.setTitle("Create shortcut");
    this.contentEl.createEl("p", { text: `Opens: ${this.target.path}`, cls: "file-shortcuts-target" });
    const folderSetting = new import_obsidian.Setting(this.contentEl).setName("Folder");
    const updateFolder = () => folderSetting.setDesc(this.folder.isRoot() ? "/ (vault root)" : this.folder.path);
    updateFolder();
    folderSetting.addButton((button) => button.setButtonText("Choose folder").onClick(() => {
      if (this.busy) return;
      new FolderPicker(this.app, (folder) => {
        this.folder = folder;
        updateFolder();
      }).open();
    }));
    const preview = this.contentEl.createEl("p", { cls: "file-shortcuts-target" });
    const updatePreview = () => {
      preview.setText(`Filename: ${this.name.replace(/\.obslink$/i, "")}.obslink`);
    };
    let nameInput;
    new import_obsidian.Setting(this.contentEl).setName("Shortcut name").addText((text) => {
      nameInput = text.inputEl;
      text.setValue(this.name).onChange((value) => {
        this.name = value;
        updatePreview();
      });
      text.inputEl.addEventListener("keydown", (event) => {
        if (event.key === "Enter" && !event.isComposing) {
          event.preventDefault();
          void submit();
        }
      });
    });
    updatePreview();
    const errorEl = this.contentEl.createEl("p", { cls: "file-shortcuts-error", attr: { role: "alert" } });
    let createButton;
    const submit = async () => {
      if (this.busy) return;
      errorEl.empty();
      try {
        const filename = shortcutName(this.name);
        if (this.app.vault.getAbstractFileByPath(this.folder.path) !== this.folder) throw new Error("The selected folder no longer exists. Choose another folder.");
        const path = this.folder.isRoot() ? filename : `${this.folder.path}/${filename}`;
        if (this.app.vault.getAbstractFileByPath(path)) throw new Error("A file with this name already exists. Choose another name or folder.");
        this.busy = true;
        createButton.setDisabled(true);
        await this.create(path, this.folder);
        this.close();
      } catch (error) {
        errorEl.setText(error instanceof Error ? error.message : "Could not create shortcut.");
      } finally {
        this.busy = false;
        createButton.setDisabled(false);
      }
    };
    new import_obsidian.Setting(this.contentEl).addButton((button) => button.setButtonText("Cancel").onClick(() => {
      if (!this.busy) this.close();
    })).addButton((button) => {
      createButton = button;
      button.setButtonText("Create shortcut").setCta().onClick(submit);
    });
    nameInput?.focus();
    nameInput?.select();
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/shortcut-view.ts
var import_obsidian2 = require("obsidian");
var ShortcutView = class extends import_obsidian2.FileView {
  constructor(leaf, actions) {
    super(leaf);
    this.actions = actions;
    this.generation = 0;
    this.redirectTimer = null;
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return this.file?.basename ?? "File shortcut";
  }
  getIcon() {
    return "file-symlink";
  }
  canAcceptExtension(extension) {
    return extension.toLowerCase() === EXTENSION;
  }
  cancelRedirect() {
    this.generation++;
    if (this.redirectTimer !== null) window.clearTimeout(this.redirectTimer);
    this.redirectTimer = null;
  }
  async onLoadFile(file) {
    this.cancelRedirect();
    const generation = this.generation;
    this.contentEl.empty();
    this.contentEl.createEl("p", { text: "Opening original file\u2026" });
    try {
      const target = await this.actions.resolve(file);
      if (generation !== this.generation || this.file !== file || this.leaf.view !== this) return;
      this.redirectTimer = window.setTimeout(() => {
        this.redirectTimer = null;
        if (generation !== this.generation || this.file !== file || this.leaf.view !== this) return;
        void this.leaf.openFile(target).catch((error) => {
          if (this.leaf.view === this && generation === this.generation) this.showError(file, error);
        });
      }, 0);
    } catch (error) {
      if (generation === this.generation && this.file === file && this.leaf.view === this) this.showError(file, error);
    }
  }
  showError(file, error) {
    this.contentEl.empty();
    this.contentEl.createEl("h2", { text: "Unable to open shortcut" });
    this.contentEl.createEl("p", { text: error instanceof Error ? error.message : "Could not open the target file." });
    const retry = this.contentEl.createEl("button", { text: "Try again" });
    retry.addEventListener("click", () => {
      void this.onLoadFile(file);
    });
    const repair = this.contentEl.createEl("button", { text: "Choose target file", cls: "mod-cta file-shortcuts-repair" });
    repair.addEventListener("click", () => this.actions.repair(file, () => {
      if (this.file === file && this.leaf.view === this) void this.onLoadFile(file);
    }));
  }
  async onUnloadFile() {
    this.cancelRedirect();
  }
  onunload() {
    this.cancelRedirect();
    super.onunload();
  }
};

// src/main.ts
var FileShortcutsPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.lastFolder = "/";
    this.renameQueue = Promise.resolve();
  }
  async onload() {
    const saved = await this.loadData();
    if (typeof saved?.lastFolder === "string") this.lastFolder = saved.lastFolder;
    this.registerView(VIEW_TYPE, (leaf) => new ShortcutView(leaf, {
      resolve: (file) => this.resolve(file),
      repair: (file, onRepaired) => this.repair(file, onRepaired)
    }));
    this.registerExtensions([EXTENSION], VIEW_TYPE);
    this.registerEvent(this.app.workspace.on("file-menu", (menu, file) => {
      if (file instanceof import_obsidian3.TFile) {
        menu.addItem((item) => item.setTitle("Create shortcut\u2026").setIcon("file-symlink").onClick(() => {
          void this.createFor(file);
        }));
        if (file.extension.toLowerCase() === EXTENSION) {
          menu.addItem((item) => item.setTitle("Change shortcut target\u2026").setIcon("file-pen-line").onClick(() => this.repair(file)));
        }
      } else if (file instanceof import_obsidian3.TFolder) {
        menu.addItem((item) => item.setTitle("Create shortcut here\u2026").setIcon("file-symlink").onClick(() => this.pickTarget(file)));
      }
    }));
    this.addCommand({
      id: "create-shortcut",
      name: "Create shortcut to current file",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!file) return false;
        if (!checking) void this.createFor(file);
        return true;
      }
    });
    this.addCommand({ id: "choose-file-for-shortcut", name: "Choose a file and create shortcut", callback: () => this.pickTarget() });
    this.registerEvent(this.app.vault.on("rename", (file, oldPath) => {
      const newPath = file.path;
      const folder = file instanceof import_obsidian3.TFolder;
      if (folder && (this.lastFolder === oldPath || this.lastFolder.startsWith(`${oldPath}/`))) {
        this.lastFolder = movedTarget(this.lastFolder, oldPath, newPath, true);
        void this.saveData({ lastFolder: this.lastFolder }).catch((error) => console.error("[file-shortcuts] Failed to save folder preference", error));
      }
      this.renameQueue = this.renameQueue.then(() => this.updateTargets(oldPath, newPath, folder)).catch((error) => {
        console.error("[file-shortcuts] Could not update shortcut targets", error);
        new import_obsidian3.Notice("Some shortcut targets could not be updated. Use Change shortcut target to repair them.");
      });
    }));
  }
  async resolve(file) {
    await this.renameQueue;
    return resolveShortcut(file, {
      read: (entry) => this.app.vault.read(entry),
      getFile: (path) => {
        const entry = this.app.vault.getAbstractFileByPath(path);
        return entry instanceof import_obsidian3.TFile ? entry : null;
      }
    });
  }
  pickTarget(folder) {
    new FilePicker(this.app, (file) => {
      void this.createFor(file, folder);
    }).open();
  }
  async createFor(file, folder) {
    try {
      const target = await this.resolve(file);
      const previous = this.app.vault.getAbstractFileByPath(this.lastFolder);
      const destination = folder ?? (previous instanceof import_obsidian3.TFolder ? previous : this.app.vault.getRoot());
      new CreateShortcutModal(this.app, target, destination, async (path, selectedFolder) => {
        if (this.app.vault.getAbstractFileByPath(target.path) !== target) throw new Error("The target file no longer exists.");
        await this.app.vault.create(path, serializeShortcut(target.path));
        this.lastFolder = selectedFolder.path;
        try {
          await this.saveData({ lastFolder: this.lastFolder });
        } catch (error) {
          console.error("[file-shortcuts] Failed to save folder preference", error);
        }
        new import_obsidian3.Notice(`Shortcut created: ${path}`);
      }).open();
    } catch (error) {
      new import_obsidian3.Notice(error instanceof Error ? error.message : "Could not create shortcut.");
    }
  }
  repair(shortcut, onRepaired) {
    new FilePicker(this.app, (chosen) => {
      void (async () => {
        try {
          const target = await this.resolve(chosen);
          if (target === shortcut) throw new Error("A shortcut cannot point to itself.");
          await this.app.vault.modify(shortcut, serializeShortcut(target.path));
          new import_obsidian3.Notice("Shortcut target updated.");
          onRepaired?.();
        } catch (error) {
          new import_obsidian3.Notice(error instanceof Error ? error.message : "Could not update shortcut.");
        }
      })();
    }).open();
  }
  async updateTargets(oldPath, newPath, folder) {
    let failed = false;
    for (const shortcut of this.app.vault.getFiles().filter((file) => file.extension.toLowerCase() === EXTENSION)) {
      try {
        const content = await this.app.vault.read(shortcut);
        let target;
        try {
          target = parseShortcut(content).target;
        } catch {
          continue;
        }
        if (movedTarget(target, oldPath, newPath, folder) === target) continue;
        await this.app.vault.process(shortcut, (latest) => {
          try {
            const data = parseShortcut(latest);
            const moved = movedTarget(data.target, oldPath, newPath, folder);
            return moved === data.target ? latest : serializeShortcut(moved);
          } catch {
            return latest;
          }
        });
      } catch (error) {
        failed = true;
        console.error("[file-shortcuts] Failed to update", shortcut.path, error);
      }
    }
    if (failed) throw new Error("One or more shortcuts could not be updated.");
  }
};
