/* File Shortcuts — generated by npm run build. Source: src/main.ts */
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FileShortcutsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/pdf-browser.ts
var import_obsidian2 = require("obsidian");

// src/pdf-catalog.ts
var import_obsidian = require("obsidian");

// src/shortcut.ts
var EXTENSION = "obslink";
var VIEW_TYPE = "file-shortcut";
function validateTarget(path) {
  if (typeof path !== "string" || !path || path.startsWith("/") || /[\\\x00-\x1f:]/.test(path)) {
    throw new Error("The shortcut must point to a file inside this vault.");
  }
  if (path.split("/").some((part) => !part || part === "." || part === "..")) {
    throw new Error("The shortcut contains an invalid vault path.");
  }
  return path;
}
function parseShortcut(content) {
  let value;
  try {
    value = JSON.parse(content);
  } catch {
    throw new Error("This shortcut is not valid JSON. Choose a target file to repair it.");
  }
  if (!value || typeof value !== "object" || !("version" in value) || value.version !== 1 || !("target" in value)) {
    throw new Error("This file is not a supported version 1 shortcut.");
  }
  return { version: 1, target: validateTarget(value.target) };
}
function serializeShortcut(target) {
  return JSON.stringify({ version: 1, target: validateTarget(target) }, null, 2) + "\n";
}
function shortcutName(input) {
  const name = input.trim().replace(/\.obslink$/i, "").trim();
  if (!name || /[<>:"/\\|?*\x00-\x1f]/.test(name) || /[. ]$/.test(name) || name.startsWith(".")) {
    throw new Error("Enter a filename without slashes or special characters.");
  }
  if (/^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i.test(name)) {
    throw new Error("This filename is reserved on Windows. Please choose another name.");
  }
  if (name.length > 180) throw new Error("Please use a shorter shortcut name (180 characters or less).");
  return `${name}.${EXTENSION}`;
}
function movedTarget(target, oldPath, newPath, folder) {
  if (target === oldPath) return newPath;
  if (folder && target.startsWith(`${oldPath}/`)) return newPath + target.slice(oldPath.length);
  return target;
}
async function resolveShortcut(file, vault) {
  const visited = /* @__PURE__ */ new Set();
  let current = file;
  while (current.extension.toLowerCase() === EXTENSION) {
    if (visited.has(current.path)) throw new Error("These shortcuts form a loop. Choose a different target file.");
    if (visited.size >= 32) throw new Error("This shortcut chain is too long. Point it directly to the original file.");
    visited.add(current.path);
    const { target } = parseShortcut(await vault.read(current));
    const next = vault.getFile(target);
    if (!next) throw new Error(`Target file not found: ${target}`);
    current = next;
  }
  return current;
}

// src/pdf-catalog.ts
function entryFrom(file, metadata = {}, shortcuts = []) {
  const imported = typeof metadata.importedAt === "string" ? Date.parse(metadata.importedAt) : NaN;
  const exact = Number.isFinite(imported) && imported > 0;
  const created = file.stat?.ctime ?? 0;
  return {
    file,
    title: typeof metadata.title === "string" && metadata.title.trim() ? metadata.title : file.basename,
    key: typeof metadata.attachmentKey === "string" ? metadata.attachmentKey : file.basename,
    timestamp: exact ? imported : created,
    dateSource: exact ? "import" : created > 0 ? "created" : "unknown",
    shortcuts
  };
}
function selectEntries(entries, search, filter, now = Date.now()) {
  const terms = search.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);
  return entries.filter((entry) => {
    if (filter === "unlinked" && entry.shortcuts.length) return false;
    if (filter === "recent" && (entry.timestamp < now - 7 * 864e5 || entry.timestamp > now)) return false;
    const haystack = [entry.title, entry.key, entry.file.path, ...entry.shortcuts].join(" ").toLocaleLowerCase();
    return terms.every((term) => haystack.includes(term));
  }).sort((a, b) => b.timestamp - a.timestamp || a.title.localeCompare(b.title));
}
function suggestedName(title) {
  const name = title.replace(/[<>:"/\\|?*\x00-\x1f]/g, " ").replace(/\s+/g, " ").trim().replace(/^\.+/, "").slice(0, 160).replace(/[. ]+$/, "");
  return !name || /^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i.test(name) ? `Paper ${name || "shortcut"}` : name;
}
async function readPdfMetadata(app) {
  const path = `${app.vault.configDir}/plugins/obsidian-zotero-bridge/data.json`;
  const metadata = /* @__PURE__ */ new Map();
  let warning = "";
  if (app.vault.adapter && await app.vault.adapter.exists(path)) {
    try {
      const data = JSON.parse(await app.vault.adapter.read(path));
      for (const [vaultPath, value] of Object.entries(data.pdfs ?? {})) {
        if (value && typeof value === "object") metadata.set(vaultPath, value);
      }
    } catch {
      warning = "Could not read Bridge metadata. Showing filenames and file creation dates.";
    }
  } else {
    warning = "No Bridge metadata found. Showing PDFs in Zotero PDFs. Update Bridge to save titles and import dates.";
  }
  return { metadata, warning };
}
async function loadPdfCatalog(app) {
  const loaded = await readPdfMetadata(app);
  const metadata = loaded.metadata;
  let warning = loaded.warning;
  const files = app.vault.getFiles();
  const entries = files.filter((file) => file.extension.toLowerCase() === "pdf" && (metadata.has(file.path) || file.path.startsWith("Zotero PDFs/"))).map((file) => entryFrom(file, metadata.get(file.path)));
  const byPath = new Map(entries.map((entry) => [entry.file.path, entry]));
  const shortcuts = files.filter((file) => file.extension.toLowerCase() === EXTENSION);
  let invalid = 0;
  for (const shortcut of shortcuts) {
    try {
      const target = await resolveShortcut(shortcut, {
        read: (file) => app.vault.read(file),
        getFile: (targetPath) => {
          const file = app.vault.getAbstractFileByPath(targetPath);
          return file instanceof import_obsidian.TFile ? file : null;
        }
      });
      byPath.get(target.path)?.shortcuts.push(shortcut.path);
    } catch {
      invalid++;
    }
  }
  if (invalid) warning += ` ${invalid} unreadable or broken shortcut(s) could not be indexed.`;
  return { entries, warning: warning.trim() };
}

// src/pdf-browser.ts
var PdfBrowser = class extends import_obsidian2.Modal {
  constructor(app, create) {
    super(app);
    this.create = create;
    this.entries = [];
    this.search = "";
    this.filter = "all";
    this.generation = 0;
    this.limit = 50;
  }
  onOpen() {
    this.modalEl.addClass("file-shortcuts-browser");
    this.setTitle("Imported PDFs");
    this.contentEl.createEl("p", { text: "Find a paper, open its PDF, or create a shortcut. Newest files appear first.", cls: "file-shortcuts-target" });
    new import_obsidian2.Setting(this.contentEl).setName("Search").addSearch((input) => input.setPlaceholder("Paper title, attachment key, or path\u2026").onChange((value) => {
      this.search = value;
      this.limit = 50;
      this.render();
    }));
    new import_obsidian2.Setting(this.contentEl).setName("Show").addDropdown((dropdown) => dropdown.addOption("all", "All imported PDFs").addOption("recent", "Recent \u2014 last 7 days").addOption("unlinked", "Without a shortcut").onChange((value) => {
      this.filter = value;
      this.limit = 50;
      this.render();
    })).addButton((button) => button.setButtonText("Reload list").onClick(() => {
      void this.reload();
    })).addButton((button) => button.setButtonText("Refresh titles from Zotero").onClick(async () => {
      const bridge = this.app.plugins?.getPlugin("obsidian-zotero-bridge");
      if (!bridge?.refreshImportedPdfMetadata) {
        new import_obsidian2.Notice("Enable Zotero Bridge 0.1.19 or newer to refresh titles.");
        return;
      }
      button.setDisabled(true);
      try {
        const result = await bridge.refreshImportedPdfMetadata();
        new import_obsidian2.Notice(`Updated ${result.updated} titles; ${result.unmatched} not found or ambiguous.`);
        if (this.results.isConnected) await this.reload();
      } catch {
        new import_obsidian2.Notice("Could not refresh titles. Open Zotero with Companion enabled and try again. Cached titles are still available.");
      } finally {
        button.setDisabled(false);
      }
    }));
    this.status = this.contentEl.createEl("p", { cls: "file-shortcuts-target", attr: { role: "status" } });
    this.results = this.contentEl.createDiv({ cls: "file-shortcuts-results" });
    void this.reload();
  }
  async reload() {
    const generation = ++this.generation;
    this.status.setText("Loading imported PDFs\u2026");
    try {
      const catalog = await loadPdfCatalog(this.app);
      if (generation !== this.generation) return;
      this.entries = catalog.entries;
      this.status.setText(catalog.warning || "Older files use file creation time (approximate). Refresh titles once to identify existing imports.");
      this.render();
    } catch (error) {
      if (generation === this.generation) this.status.setText(`Could not load PDFs: ${error instanceof Error ? error.message : String(error)}`);
    }
  }
  render() {
    if (!this.results) return;
    this.results.empty();
    const selected = selectEntries(this.entries, this.search, this.filter);
    this.results.createEl("p", { text: `${selected.length} of ${this.entries.length} PDFs`, cls: "file-shortcuts-target" });
    if (!selected.length) this.results.createEl("p", { text: "No matching PDFs. Try All imported PDFs or clear the search." });
    for (const entry of selected.slice(0, this.limit)) {
      const card = this.results.createDiv({ cls: "file-shortcuts-pdf-card" });
      card.createEl("h3", { text: entry.title });
      card.createEl("p", { text: entry.file.path, cls: "file-shortcuts-target" });
      const when = entry.timestamp > 0 ? new Date(entry.timestamp).toLocaleString() : "Unknown";
      card.createEl("p", { text: `${entry.dateSource === "import" ? "Imported" : entry.dateSource === "created" ? "File created (approximate)" : "Date"}: ${when}` });
      card.createEl("p", { text: entry.shortcuts.length ? `Shortcuts: ${entry.shortcuts.join(" \xB7 ")}` : "No shortcut yet", cls: "file-shortcuts-target" });
      new import_obsidian2.Setting(card).addButton((button) => button.setButtonText("Open PDF").onClick(async () => {
        try {
          await this.app.workspace.getLeaf("tab").openFile(entry.file);
          this.close();
        } catch {
          new import_obsidian2.Notice("Could not open the PDF. Reload the list to check whether it still exists.");
        }
      })).addButton((button) => button.setButtonText("Create shortcut").setCta().onClick(() => this.create(entry.file, entry.title, () => {
        if (this.results.isConnected) void this.reload();
      })));
    }
    if (selected.length > this.limit) new import_obsidian2.Setting(this.results).addButton((button) => button.setButtonText("Show more").onClick(() => {
      this.limit += 50;
      this.render();
    }));
  }
  onClose() {
    this.generation++;
    this.contentEl.empty();
  }
};

// src/dialogs.ts
var import_obsidian3 = require("obsidian");
var FilePicker = class extends import_obsidian3.FuzzySuggestModal {
  constructor(app, choose) {
    super(app);
    this.choose = choose;
    this.metadata = /* @__PURE__ */ new Map();
    this.setPlaceholder("Search title or path \u2014 newest imports / files first");
  }
  async prepare() {
    try {
      this.metadata = (await readPdfMetadata(this.app)).metadata;
    } catch {
      this.metadata.clear();
    }
    return this;
  }
  getItems() {
    return this.app.vault.getFiles().filter((file) => file.extension.toLowerCase() !== EXTENSION).sort((a, b) => entryFrom(b, this.metadata.get(b.path)).timestamp - entryFrom(a, this.metadata.get(a.path)).timestamp || this.getItemText(a).localeCompare(this.getItemText(b)));
  }
  getItemText(file) {
    const title = this.metadata.get(file.path)?.title;
    return title ? `${title} \u2014 ${file.path}` : file.path;
  }
  renderSuggestion(match, el) {
    const entry = entryFrom(match.item, this.metadata.get(match.item.path));
    el.createDiv({ text: entry.title });
    const date = entry.timestamp > 0 ? new Date(entry.timestamp).toLocaleString() : "Unknown";
    el.createDiv({ text: `${entry.file.path} \xB7 ${entry.dateSource === "import" ? "Imported" : "File created (approximate)"}: ${date}`, cls: "file-shortcuts-picker-detail" });
  }
  onChooseItem(file) {
    if (file.extension.toLowerCase() === EXTENSION) return;
    this.choose(file, this.metadata.get(file.path)?.title);
  }
};
var FolderPicker = class extends import_obsidian3.FuzzySuggestModal {
  constructor(app, choose) {
    super(app);
    this.choose = choose;
    this.setPlaceholder("Choose a folder for the shortcut");
  }
  getItems() {
    const root = this.app.vault.getRoot();
    const folders = this.app.vault.getAllLoadedFiles().filter((file) => file instanceof import_obsidian3.TFolder && file !== root).sort((a, b) => a.path.localeCompare(b.path));
    return [root, ...folders];
  }
  getItemText(folder) {
    return folder.isRoot() ? "/ (vault root)" : folder.path;
  }
  onChooseItem(folder) {
    this.choose(folder);
  }
};
var CreateShortcutModal = class extends import_obsidian3.Modal {
  constructor(app, target, folder, create, initialName) {
    super(app);
    this.target = target;
    this.folder = folder;
    this.create = create;
    this.layout = "file";
    this.busy = false;
    this.name = initialName ?? target.basename;
  }
  onOpen() {
    this.setTitle("Create shortcut");
    this.contentEl.createEl("p", { text: `Opens: ${this.target.path}`, cls: "file-shortcuts-target" });
    const folderSetting = new import_obsidian3.Setting(this.contentEl).setName("Folder");
    const updateFolder = () => folderSetting.setDesc(this.folder.isRoot() ? "/ (vault root)" : this.folder.path);
    updateFolder();
    folderSetting.addButton((button) => button.setButtonText("Choose folder").onClick(() => {
      if (this.busy) return;
      new FolderPicker(this.app, (folder) => {
        this.folder = folder;
        updateFolder();
      }).open();
    }));
    const layoutSetting = new import_obsidian3.Setting(this.contentEl).setName("Create as");
    layoutSetting.addDropdown((dropdown) => dropdown.addOption("file", "Shortcut file only").addOption("folder", "Folder containing shortcut").setValue(this.layout).onChange((value) => {
      this.layout = value === "folder" ? "folder" : "file";
      updatePreview();
    }));
    const preview = this.contentEl.createEl("p", { cls: "file-shortcuts-target" });
    const updatePreview = () => {
      const stem = this.name.replace(/\.obslink$/i, "");
      const typeName = this.target.extension ? this.target.extension.toUpperCase() : "FILE";
      preview.setText(this.layout === "folder" ? `Creates: ${stem}/${typeName}.obslink` : `Creates: ${stem}.obslink`);
    };
    let nameInput;
    new import_obsidian3.Setting(this.contentEl).setName("Shortcut name").addText((text) => {
      nameInput = text.inputEl;
      text.setValue(this.name).onChange((value) => {
        this.name = value;
        updatePreview();
      });
      text.inputEl.addEventListener("keydown", (event) => {
        if (event.key === "Enter" && !event.isComposing) {
          event.preventDefault();
          void submit();
        }
      });
    });
    updatePreview();
    const errorEl = this.contentEl.createEl("p", { cls: "file-shortcuts-error", attr: { role: "alert" } });
    let createButton;
    const submit = async () => {
      if (this.busy) return;
      errorEl.empty();
      try {
        const filename = shortcutName(this.name);
        if (this.app.vault.getAbstractFileByPath(this.folder.path) !== this.folder) throw new Error("The selected folder no longer exists. Choose another folder.");
        const stem = filename.slice(0, -(EXTENSION.length + 1));
        const containerPath = this.layout === "folder" ? this.folder.isRoot() ? stem : `${this.folder.path}/${stem}` : void 0;
        const typeName = this.target.extension ? this.target.extension.toUpperCase() : "FILE";
        const path = containerPath ? `${containerPath}/${typeName}.${EXTENSION}` : this.folder.isRoot() ? filename : `${this.folder.path}/${filename}`;
        if (containerPath && this.app.vault.getAbstractFileByPath(containerPath)) throw new Error("A folder or file with this name already exists. Choose another name or folder.");
        if (this.app.vault.getAbstractFileByPath(path)) throw new Error("A file with this name already exists. Choose another name or folder.");
        this.busy = true;
        createButton.setDisabled(true);
        await this.create(path, this.folder, containerPath);
        this.close();
      } catch (error) {
        errorEl.setText(error instanceof Error ? error.message : "Could not create shortcut.");
      } finally {
        this.busy = false;
        createButton.setDisabled(false);
      }
    };
    new import_obsidian3.Setting(this.contentEl).addButton((button) => button.setButtonText("Cancel").onClick(() => {
      if (!this.busy) this.close();
    })).addButton((button) => {
      createButton = button;
      button.setButtonText("Create shortcut").setCta().onClick(submit);
    });
    nameInput?.focus();
    nameInput?.select();
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/shortcut-view.ts
var import_obsidian4 = require("obsidian");
var ShortcutView = class extends import_obsidian4.FileView {
  constructor(leaf, actions) {
    super(leaf);
    this.actions = actions;
    this.generation = 0;
    this.redirectTimer = null;
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return this.file?.basename ?? "File shortcut";
  }
  getIcon() {
    return "file-symlink";
  }
  canAcceptExtension(extension) {
    return extension.toLowerCase() === EXTENSION;
  }
  cancelRedirect() {
    this.generation++;
    if (this.redirectTimer !== null) window.clearTimeout(this.redirectTimer);
    this.redirectTimer = null;
  }
  async onLoadFile(file) {
    this.cancelRedirect();
    const generation = this.generation;
    this.contentEl.empty();
    this.contentEl.createEl("p", { text: "Opening original file\u2026" });
    try {
      const target = await this.actions.resolve(file);
      if (generation !== this.generation || this.file !== file || this.leaf.view !== this) return;
      this.redirectTimer = window.setTimeout(() => {
        this.redirectTimer = null;
        if (generation !== this.generation || this.file !== file || this.leaf.view !== this) return;
        void this.leaf.openFile(target).catch((error) => {
          if (this.leaf.view === this && generation === this.generation) this.showError(file, error);
        });
      }, 0);
    } catch (error) {
      if (generation === this.generation && this.file === file && this.leaf.view === this) this.showError(file, error);
    }
  }
  showError(file, error) {
    this.contentEl.empty();
    this.contentEl.createEl("h2", { text: "Unable to open shortcut" });
    this.contentEl.createEl("p", { text: error instanceof Error ? error.message : "Could not open the target file." });
    const retry = this.contentEl.createEl("button", { text: "Try again" });
    retry.addEventListener("click", () => {
      void this.onLoadFile(file);
    });
    const repair = this.contentEl.createEl("button", { text: "Choose target file", cls: "mod-cta file-shortcuts-repair" });
    repair.addEventListener("click", () => this.actions.repair(file, () => {
      if (this.file === file && this.leaf.view === this) void this.onLoadFile(file);
    }));
  }
  async onUnloadFile() {
    this.cancelRedirect();
  }
  onunload() {
    this.cancelRedirect();
    super.onunload();
  }
};

// src/main.ts
var FileShortcutsPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.lastFolder = "/";
    this.renameQueue = Promise.resolve();
  }
  async onload() {
    const saved = await this.loadData();
    if (typeof saved?.lastFolder === "string") this.lastFolder = saved.lastFolder;
    this.registerView(VIEW_TYPE, (leaf) => new ShortcutView(leaf, {
      resolve: (file) => this.resolve(file),
      repair: (file, onRepaired) => this.repair(file, onRepaired)
    }));
    this.registerExtensions([EXTENSION], VIEW_TYPE);
    const browsePdfs = () => new PdfBrowser(this.app, (file, title, done) => this.createFor(file, void 0, title, done)).open();
    this.addRibbonIcon("library", "Browse imported PDFs", browsePdfs);
    this.addCommand({ id: "browse-imported-pdfs", name: "Browse imported PDFs", callback: browsePdfs });
    this.registerEvent(this.app.workspace.on("file-menu", (menu, file) => {
      if (file instanceof import_obsidian5.TFile) {
        if (file.extension.toLowerCase() !== EXTENSION) menu.addItem((item) => item.setTitle("Create shortcut\u2026").setIcon("file-symlink").onClick(() => {
          void this.createFor(file);
        }));
        if (file.extension.toLowerCase() === EXTENSION) {
          menu.addItem((item) => item.setTitle("Change shortcut target\u2026").setIcon("file-pen-line").onClick(() => this.repair(file)));
        }
      } else if (file instanceof import_obsidian5.TFolder) {
        menu.addItem((item) => item.setTitle("Create shortcut here\u2026").setIcon("file-symlink").onClick(() => this.pickTarget(file)));
      }
    }));
    this.addCommand({
      id: "create-shortcut",
      name: "Create shortcut to current file",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!file || file.extension.toLowerCase() === EXTENSION) return false;
        if (!checking) void this.createFor(file);
        return true;
      }
    });
    this.addCommand({ id: "choose-file-for-shortcut", name: "Choose a file and create shortcut", callback: () => this.pickTarget() });
    this.registerEvent(this.app.vault.on("rename", (file, oldPath) => {
      const newPath = file.path;
      const folder = file instanceof import_obsidian5.TFolder;
      if (folder && (this.lastFolder === oldPath || this.lastFolder.startsWith(`${oldPath}/`))) {
        this.lastFolder = movedTarget(this.lastFolder, oldPath, newPath, true);
        void this.saveData({ lastFolder: this.lastFolder }).catch((error) => console.error("[file-shortcuts] Failed to save folder preference", error));
      }
      this.renameQueue = this.renameQueue.then(() => this.updateTargets(oldPath, newPath, folder)).catch((error) => {
        console.error("[file-shortcuts] Could not update shortcut targets", error);
        new import_obsidian5.Notice("Some shortcut targets could not be updated. Use Change shortcut target to repair them.");
      });
    }));
  }
  async resolve(file) {
    await this.renameQueue;
    return resolveShortcut(file, {
      read: (entry) => this.app.vault.read(entry),
      getFile: (path) => {
        const entry = this.app.vault.getAbstractFileByPath(path);
        return entry instanceof import_obsidian5.TFile ? entry : null;
      }
    });
  }
  pickTarget(folder) {
    const picker = new FilePicker(this.app, (file, title) => {
      void this.createFor(file, folder, title);
    });
    void picker.prepare().then(() => picker.open());
  }
  async createFor(file, folder, title, done) {
    try {
      if (file.extension.toLowerCase() === EXTENSION) throw new Error("Choose an original file, not a shortcut.");
      const target = await this.resolve(file);
      if (!title) {
        try {
          title = (await readPdfMetadata(this.app)).metadata.get(target.path)?.title;
        } catch {
        }
      }
      const previous = this.app.vault.getAbstractFileByPath(this.lastFolder);
      const destination = folder ?? (previous instanceof import_obsidian5.TFolder ? previous : this.app.vault.getRoot());
      new CreateShortcutModal(this.app, target, destination, async (path, selectedFolder, containerPath) => {
        if (this.app.vault.getAbstractFileByPath(target.path) !== target) throw new Error("The target file no longer exists.");
        if (containerPath) await this.app.vault.createFolder(containerPath);
        await this.app.vault.create(path, serializeShortcut(target.path));
        this.lastFolder = selectedFolder.path;
        try {
          await this.saveData({ lastFolder: this.lastFolder });
        } catch (error) {
          console.error("[file-shortcuts] Failed to save folder preference", error);
        }
        new import_obsidian5.Notice(`Shortcut created: ${path}`);
        done?.();
      }, title ? suggestedName(title) : void 0).open();
    } catch (error) {
      new import_obsidian5.Notice(error instanceof Error ? error.message : "Could not create shortcut.");
    }
  }
  repair(shortcut, onRepaired) {
    const picker = new FilePicker(this.app, (chosen) => {
      void (async () => {
        try {
          const target = await this.resolve(chosen);
          if (target === shortcut) throw new Error("A shortcut cannot point to itself.");
          await this.app.vault.modify(shortcut, serializeShortcut(target.path));
          new import_obsidian5.Notice("Shortcut target updated.");
          onRepaired?.();
        } catch (error) {
          new import_obsidian5.Notice(error instanceof Error ? error.message : "Could not update shortcut.");
        }
      })();
    });
    void picker.prepare().then(() => picker.open());
  }
  async updateTargets(oldPath, newPath, folder) {
    let failed = false;
    for (const shortcut of this.app.vault.getFiles().filter((file) => file.extension.toLowerCase() === EXTENSION)) {
      try {
        const content = await this.app.vault.read(shortcut);
        let target;
        try {
          target = parseShortcut(content).target;
        } catch {
          continue;
        }
        if (movedTarget(target, oldPath, newPath, folder) === target) continue;
        await this.app.vault.process(shortcut, (latest) => {
          try {
            const data = parseShortcut(latest);
            const moved = movedTarget(data.target, oldPath, newPath, folder);
            return moved === data.target ? latest : serializeShortcut(moved);
          } catch {
            return latest;
          }
        });
      } catch (error) {
        failed = true;
        console.error("[file-shortcuts] Failed to update", shortcut.path, error);
      }
    }
    if (failed) throw new Error("One or more shortcuts could not be updated.");
  }
};
